### ISSUE TITLE
Post-GTK4 Checklist

### ISSUE THREAD

**Issue by jannuary** [bottlesdevs/Bottles#1598]
Regressions:
- [x] [Clipboard button not working in Health Check](https://github.com/bottlesdevs/Bottles/issues/1596)
- [x] [About dialog not sticking with parent window](https://github.com/bottlesdevs/Bottles/issues/1595)
- [x] [Overlapping text when switching between mobile and desktop UIs](https://github.com/bottlesdevs/Bottles/issues/1594)
- [x] [Visual issues with dropdown menu](https://github.com/bottlesdevs/Bottles/issues/1593)
- [x] [Mobile mode doesn't open content](https://github.com/bottlesdevs/Bottles/issues/1592)
- [x] Keyboard nav broken in the bottle view (when unfolded)
- [x] https://github.com/bottlesdevs/Bottles/issues/2085

Cleanups:
- [x] [Replace ComboBoxes with ComboRows](https://github.com/bottlesdevs/Bottles/issues/454)
- [ ] #2207
- [x] Use toasts where applicable

Nitpicks/Consistency:
- [x] Use title case
- [x] Use ellipses
- [x] Some ActionRows have no activatable-widget 
- [x] Every closable dialog should be closable by Esc
- [ ] Can't create a bottle with Enter

### non-blocking for GNOME Circle
In design phase:
- [ ] Update Onboarding
- [x] Update Bottle View
- [ ] Improve appearance of installable things

**Comment by mirkobrombin** [comment]
Toasts:
- [ ] component installed
- [ ] component installation failed
- [ ] dependency installation failed
- [ ] text copied in health check
- [ ] program launched > Launching program {}..

**Comment by mirkobrombin** [comment]
> Keyboard nav broken in the bottle view (when unfolded)

I think we should simply force a min-size as Bottles is not a mobile app

**Comment by jannuary** [comment]
It's not relevant anyway - it seems it's been silently fixed since.

**Comment by dontdieych** [comment]
```
Operating System: Arch Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.12-arch1-1 (64-bit)
Graphics Platform: X11

gtk4: 4.8.1-1
```

- 15" laptop
- 4k resolution
- KDE Plasma 5 + 300% scaling (my eyesight not good :D )
- X11 (Xorg) DPI set to 288 (96 * 3)

I've found the same problem on two gtk4 apps.

AUR [ `bottles-git` ](https://aur.archlinux.org/packages/bottles-git) version

![Screenshot_20221002_051158](https://user-images.githubusercontent.com/6509673/193428475-1a125dfe-23e5-492d-923c-245f95f1ed66.png)

Arch official repo[ `easyeffects` ](https://archlinux.org/packages/community/x86_64/easyeffects/) (pipewire related app)

![Screenshot_20221002_042807](https://user-images.githubusercontent.com/6509673/193428482-648234d7-d881-4006-be00-03b45c2a9a78.png)

Both are showing too big font scaling. Compare with normal kate editor's font size at background.

One weird thing is pre-built `bottles` from [chaoticaur](https://archlinux.pkgs.org/rolling/chaotic-aur-x86_64/bottles-1:2022.5.28-5-x86_64.pkg.tar.zst.html) repo is OK.

```
a@archlinux ~/.c/y/bottles (master)> yay -Q bottles 
bottles 1:2022.5.28-5
```
![Screenshot_20221002_051611](https://user-images.githubusercontent.com/6509673/193428499-82f9c7bc-7f2b-4359-8a83-32df02c9c71a.png)

**Comment by jannuary** [comment]
Please file an issue - this one is solely for organization purposes.

**Comment by jannuary** [comment]
I think we can close this - most issues have been fixed, some aren't relevant anymore and some would be better separately.
