### ISSUE TITLE
GNOME Circle inclusion checklist

### ISSUE THREAD

**Issue by TheEvilSkeleton** [bottlesdevs/Bottles#2126]
This is a checklist that we need to address before getting it to [GNOME Circle](https://gitlab.gnome.org/Teams/Circle/-/issues/61):

- [x] Two "Programs" views (https://github.com/bottlesdevs/Bottles/pull/2203)
  | a | b |
  | --- | --- |
  | ![image](https://gitlab.gnome.org/Teams/Circle/uploads/47950ff2110eacc5e23463f7b71d0142/image.png) | ![image](https://gitlab.gnome.org/Teams/Circle/uploads/0be65d601b559a46bbb687eb84bdd0db/image.png) |
- [x] ~~"Run Executable" is suggested and blue~~ We still want to encourage users to use this feature as they create their bottle.
- [x] Gold, etc. don't have a clear meaning (https://github.com/bottlesdevs/Bottles/pull/2215)
- [x] Upon creating a bottle, the bottle view doesn't open (https://github.com/bottlesdevs/Bottles/commit/585ad84491c2b1f42ab40367d9f612ed09afc433)

**Comment by mirkobrombin** [comment]
Grades https://maintainers.usebottles.com/installers/structure/

**Comment by TheEvilSkeleton** [comment]
> Grades https://maintainers.usebottles.com/installers/structure/

@jannuary @mirkobrombin should we rename grades in the UI? Something like this:
- Platinum -> "Works perfectly"
- Gold -> "Works with minor issues"
- Silver -> "Works with noticeable issues"
- Bronze -> "May not work"

We can reword them.

**Comment by mirkobrombin** [comment]
I'm against. Those a common words in the Wine world.

**Comment by TheEvilSkeleton** [comment]
Maybe a tooltip would suffice?

**Comment by mirkobrombin** [comment]
Probably yes
